"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# Copyright(C) 2010.  Free Stream Media Corp.  Released under the terms of
# GNU General Public License version 2.0.
# See http://www.gnu.org/licenses/gpl-2.0.html

from setuptools import setup

APP = ['flingo.py']
DATA_FILES = ['flingo.png', 'flingo.conf']
OPTIONS = {'argv_emulation': True, 'iconfile': 'flingo.icns', 'includes': ['sip', 'PyQt4']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'netifaces', 'Twisted', 'qt4reactor'],
)
