"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# Copyright(C) 2010.  Free Stream Media Corp.  Released under the terms of
# GNU General Public License version 2.0.
# See http://www.gnu.org/licenses/gpl-2.0.html
import sys
import os
from setuptools import setup, extension

sys.argv.append('py2exe')

DATA_FILES = ['flingo.png', 'flingo.conf']

if sys.platform == 'darwin':
    APP = ['flingo.py']
    OPTIONS = {'argv_emulation': True, 'iconfile': 'flingo.icns', 'includes': ['sip', 'PyQt4']}
    REC = ['py2app', 'Twisted']  #, 'qt4reactor']
    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app':OPTIONS},
        setup_requires=REC,
    )
else:
    # I get "invalid argument" when I include "bundle_files" : 1 with
    # ms_data as defined using the glob. It doesn't matter whether setup
    # is imported from distutils.core or setuptools.
    import py2exe
    from glob import glob
    path = os.path.join(os.getcwd(), "Microsoft.VC90.CRT")
    sys.path.append(path)
    ms_data = DATA_FILES  + [("Microsoft.VC90.CRT", glob(path + r'\*.*'))]

    #print "ms_data=", ms_data
    OPTIONS = {"includes" : ["sip", "PyQt4"], "packages" : ["twisted", "qt4reactor"], 'bundle_files': 1}
    REC = ["py2exe"]

    # If zipfile is None then I get a flingo.exe that won't execute.  I get an
    # error "Bug: Invalid script resource"
    setup(
        windows=[{"script": "flingo.py", "icon_resources": [(0, "flingo.ico")]}],
        data_files=ms_data,
        options={'py2exe' : OPTIONS},
        zipfile="library.zip",
    )


